name: CI

on:
    pull_request:
    push:
        branches: [ main ]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.3
                    coverage: none

            -   name: Install Composer packages
                uses: ramsey/composer-install@v3

            -   name: Run tests
                run: vendor/bin/phpunit --colors=always

    php-cs-fixer:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Set up PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.3'
                    coverage: none

            -   name: Install Composer packages
                uses: ramsey/composer-install@v3

            -   name: Run PHP CS Fixer
                run: vendor/bin/php-cs-fixer check --diff --ansi

    phpstan:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Set up PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.3'
                    coverage: none

            -   name: Install Composer packages
                uses: ramsey/composer-install@v3

            -   name: Run PHPStan
                run: vendor/bin/phpstan --ansi
